### ISSUE TITLE
Adding contraction coding

### ISSUE THREAD

**Issue by christopherahern** [christopherahern/do-PPCHE#7]
@bacovcin trying to add a column indicating contracted negation.

```
4 : {
contracted: (CP* iDoms IP*) AND (IP* iDomsMod IP*|CONJ* NEG*) AND (NEG* iDoms $n't)
-: ELSE                                                                         
}
```

`$n't` is the form of contracted negation, but this query is throwing an error:

```
---Coding corpus---
java -classpath queries/CS_2.003.04.jar csearch/CorpusSearch queries/do-support.c queries/dummy.psd

Copyright 2010 Beth Randall

CorpusSearch version 2.003.00

CorpusSearch Manual:  http://corpussearch.sourceforge.net/CS-manual/Contents.html

ERROR!  In Meat.CrankThrough:  
Exception:  Encountered "4" at line 1, column 637.
Was expecting one of:
    <EOF> 
    <COL_NUM> ...
    
Encountered "4" at line 1, column 637.
Was expecting one of:
    <EOF> 
    <COL_NUM> ...
    
CodingParse.ParseException: Encountered "4" at line 1, column 637.
Was expecting one of:
    <EOF> 
    <COL_NUM> ...
    
CodingParse.ParseException: Encountered "4" at line 1, column 637.
Was expecting one of:
    <EOF> 
    <COL_NUM> ...
    
	at CodingParse.ParseCodingQuery.generateParseException(ParseCodingQuery.java:1378)
	at CodingParse.ParseCodingQuery.jj_consume_token(ParseCodingQuery.java:1313)
	at CodingParse.ParseCodingQuery.FlushQuery(ParseCodingQuery.java:805)
	at CodingParse.ParseCodingQuery.makeCodingQueryTree(ParseCodingQuery.java:795)
	at csearch.MeatCoding.CrankThrough(MeatCoding.java:47)
	at csearch.Meat.CrankThrough(Meat.java:80)
	at csearch.CorpusSearch.main(CorpusSearch.java:66)
make: *** [queries/do-support.cod] Error 1
```

Thoughts on how to format the query to escape those characters?

**Comment by bacovcin** [comment]
My first guess is that you have a space between the number and the colon and that may cause the error. If that doesn't work, we can move on to some other debugging.

**Comment by christopherahern** [comment]
Ah, yup, that does it. facepalm. Thanks!

**Comment by bacovcin** [comment]
Happy to help.
